# permissions for end users to edit kialis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kiali-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: kiali-editor-role
rules:
- apiGroups:
  - kiali.io.my.domain
  resources:
  - kialis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kiali.io.my.domain
  resources:
  - kialis/status
  verbs:
  - get
